### ISSUE TITLE
Feature request: GitHub repo link handler URI scheme for opening repositories

### ISSUE THREAD

**Issue by Jarred-Sumner** [codespaces-contrib/gistpad#209]
**Is your feature request related to a problem? Please describe.**
Opening a public repo with GistPad to read code could be faster. 

The current process is:
1. `⌘+Shift+P`
2. `> GistPad: Open Repository`
3. Type repository name

As a point of comparison, github1s is a very fast way to view a GitHub repo's codebase from inside a web-based version of Visual Studio Code, e.g. [https://github**1s**.com/codespaces-contrib/gistpad](https://github1s.com/codespaces-contrib/gistpad) – you just add `1s` to the URL in your browser tab.

**Describe the solution you'd like**
If there was a "Open in VSCode" button on GitHub repo pages, I would click that button often – specifically for reading/searching code quickly. The simplest way to enable that would be a link handler URI scheme.

A URI scheme would be broadly useful. For example, it would let `README.md` for boilerplate repos add a `Open in VSCode` button, which would be faster than pasting `git clone` into your terminal and opening the repo in a local folder 

I would be happy to make a "Open in VSCode" button as a very simple Chrome extension (it would just add a button with the link in a good spot on repository pages). 

I do have access to Codespaces, but I don't currently use it because for writing code, I would rather use my own editor/environment.

**Comment by lostintangent** [comment]
Hey! There's actually already a protocol handler for opening a repo, though it needs to be enhanced in order to make this E2E truly shine. If you launch `vscode://vsls-contrib.gistfs/open?repo=microsoft/vscode` from your browser, that would open the VS Code repo in VS Code. If you didn't have the GistPad extension installed, it would walk you through installing it and then would open the repo. So if you wanted to create a Chrome extension, you could rely on that URL convention right now.

That said, the current protocol handler automates opening the repo, but it doesn't focus the GistPad tab and scroll the newly opened repo into view. So we could use this issue to track some enhancements that I can make to that behavior. Let me know what you think!

**Comment by Jarred-Sumner** [comment]
Thanks for getting back to me

>  If you launch vscode://vsls-contrib.gistfs/open?repo=microsoft/vscode from your browser, that would open the VS Code repo in VS Code

Wow cool!

I ended up just building this CLI tool instead: https://github.com/jarred-sumner/git-peek
